'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup(saved={},blocked=false){
 const elements=new Map(),values=new Map(Object.entries(saved));
 const element=()=>({value:'',style:{},dataset:{},classList:{add(){},remove(){},toggle(){}},setAttribute(){},addEventListener(){},showModal(){this.open=true},close(){this.open=false},focus(){},querySelector(){return element()},querySelectorAll(){return []},get innerHTML(){return this.textContent||''},set innerHTML(v){this.textContent=v}});
 const document={querySelector:s=>{if(!elements.has(s))elements.set(s,element());return elements.get(s)},querySelectorAll:()=>[],createElement:element,addEventListener(){},documentElement:{dataset:{}},body:element()};
 class Audio{constructor(){this.currentTime=0;this.duration=200;this.paused=true;this.events={}}addEventListener(name,cb){(this.events[name]??=[]).push(cb)}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true}load(){this.loaded=true}}
 const sandbox={document,window:{addEventListener(){}},navigator:{onLine:true},Audio,localStorage:{getItem:k=>{if(blocked)throw Error('blocked');return values.get(k)||null},setItem:(k,v)=>{if(blocked)throw Error('blocked');values.set(k,String(v))},removeItem:k=>values.delete(k)},setTimeout(){},clearTimeout(){},setInterval(){},URLSearchParams,location:{pathname:'/',search:'',origin:'http://test'},history:{pushState(){}},console};
 const context=vm.createContext(sandbox);const code=fs.readFileSync('public/app.js','utf8').replace('load().catch(e=>toast(e.message));','');vm.runInContext(code,context);return {run:code=>vm.runInContext(code,context),values,elements};
}
test('player initializes when preferences are corrupted or storage is blocked',()=>{assert.doesNotThrow(()=>setup({'mase-recent':'broken JSON','mase-searches':'{}'}));assert.doesNotThrow(()=>setup({},true))});
test('session recovery removes unavailable tracks and preserves position without autoplay',()=>{const app=setup({'mase-session':JSON.stringify({queue:['deleted','1','2'],position:2,current:'2',time:41})});app.run("state.tracks=[{id:1,title:'One',artist:'A',audioUrl:'/1'},{id:2,title:'Two',artist:'B',audioUrl:'/2'}];trackIndex=new Map(state.tracks.map(t=>[String(t.id),t]));restoreSession()");assert.equal(app.run('JSON.stringify(state.queue)'), '["1","2"]');assert.equal(app.run('state.queuePos'),1);assert.equal(app.run('audio.paused'),true);app.run("audio.events.loadedmetadata.forEach(fn=>fn());saveSession()");assert.equal(JSON.parse(app.values.get('mase-session')).time,41)});
test('shuffle preserves every song and next follows the visible queue',async()=>{const app=setup();assert.equal(app.run("shuffleArray(['1','2','3','4']).sort().join(',')"),'1,2,3,4');app.run("state.tracks=[{id:1,title:'One',artist:'A',audioUrl:'/1'},{id:2,title:'Two',artist:'B',audioUrl:'/2'}];trackIndex=new Map(state.tracks.map(t=>[String(t.id),t]));state.queue=['2','1'];state.queuePos=0;state.shuffle=true;next()");assert.equal(app.run('state.currentId'),'1')});
test('large libraries render a bounded first page with lazy artwork',()=>{const app=setup();app.run("state.tracks=Array.from({length:200},(_,i)=>({id:i,title:'Song',artist:'A',coverUrl:'https://example.com/cover.jpg'}));render(true)");const html=app.elements.get('#tracks').textContent;assert.equal((html.match(/<article/g)||[]).length,48);assert.equal((html.match(/loading="lazy"/g)||[]).length,48)});
test('automatic holiday calendar covers fixed and moving celebrations',()=>{const app=setup();assert.equal(app.run("holidayFor(new Date(2026,1,14)).theme"),'valentine');assert.equal(app.run("holidayFor(new Date(2026,3,5)).theme"),'easter');assert.equal(app.run("holidayFor(new Date(2026,10,26)).theme"),'thanksgiving');assert.equal(app.run("holidayFor(new Date(2026,11,24)).theme"),'winter');assert.equal(app.run("holidayFor(new Date(2026,7,12))"),null)});

test('FlyBrain learns locally and can build a guest recommendation queue',()=>{const app=setup();app.run("state.tracks=[{id:1,title:'First Light',artist:'Nova',album:'Sky',audioUrl:'/1'},{id:2,title:'Night Drive',artist:'Nova',album:'Road',audioUrl:'/2'},{id:3,title:'Quiet Room',artist:'Else',album:'Home',audioUrl:'/3'}];trackIndex=new Map(state.tracks.map(t=>[String(t.id),t]));teachFly(state.tracks[0],2);startFlyBrain()");assert.ok(Object.keys(JSON.parse(app.values.get('mase-flybrain-v1'))).length>0);assert.equal(app.run('state.flyMode'),true);assert.ok(app.run('state.queue.length')>0)});
test('catalog cache hydrates before the network and next-track warmup is bounded',()=>{const cached={at:Date.now(),tracks:[{id:1,title:'One',artist:'A',audioUrl:'/1'},{id:2,title:'Two',artist:'B',audioUrl:'/2'}]},app=setup({'mase-catalog-v1':JSON.stringify(cached)});assert.equal(app.run('catalogFromCache().length'),2);app.run("setCatalog(catalogFromCache());state.queue=['1','2'];state.queuePos=0;warmNext()");assert.equal(app.run('warmedUrl'),'/2')});
test('live radio derives the same current item and offset from the shared clock',()=>{const app=setup();app.run("state.radioSchedule=[{kind:'track',id:'1',duration:100},{kind:'voice',id:'v1',duration:10},{kind:'track',id:'2',duration:90}];state.radioStartsAt=1000000;state.radioClockOffset=0");app.run('Date.now=()=>1115000');assert.equal(app.run('radioPosition().entry.id'),'2');assert.equal(app.run('radioPosition().offset'),5);assert.equal(app.run('radioPosition().remaining'),85)});
test('live radio pause control mutes without stopping the shared broadcast',()=>{const app=setup();app.run("state.radioStation='all';audio.paused=false;audio.muted=false");app.elements.get('#play').onclick();assert.equal(app.run('audio.muted'),true);assert.equal(app.run('audio.paused'),false);app.elements.get('#play').onclick();assert.equal(app.run('audio.muted'),false);assert.equal(app.run('audio.paused'),false)});
