'use strict';
require('dotenv').config();
const path=require('node:path'),crypto=require('node:crypto'),express=require('express'),helmet=require('helmet'),cookieParser=require('cookie-parser');
const jwt=require('jsonwebtoken'),bcrypt=require('bcryptjs'),multer=require('multer');
const {rateLimit}=require('express-rate-limit'),{z}=require('zod'),{neon}=require('@neondatabase/serverless');

const isProd=process.env.NODE_ENV==='production',PORT=Number(process.env.PORT||3000);
const SECRET=process.env.JWT_SECRET,ADMIN=(process.env.ADMIN_EMAIL||'').trim().toLowerCase(),ADMIN_HASH=process.env.ADMIN_PASSWORD_HASH;
const ORIGIN=process.env.APP_ORIGIN||(process.env.VERCEL_PROJECT_PRODUCTION_URL?`https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`:`http://localhost:${PORT}`);
const GH_REPO=process.env.GITHUB_REPOSITORY||'',GH_BRANCH=process.env.GITHUB_BRANCH||'main',GH_DIR=(process.env.GITHUB_MUSIC_PATH||'music').replace(/^\/+|\/+$/g,''),GH_TOKEN=process.env.GITHUB_TOKEN||'';
const configErrors=[];
if(!SECRET||SECRET.length<32)configErrors.push('JWT_SECRET');
if(!z.string().email().safeParse(ADMIN).success)configErrors.push('ADMIN_EMAIL');
if(!/^\$2[aby]\$\d\d\$[./A-Za-z0-9]{53}$/.test(ADMIN_HASH||''))configErrors.push('ADMIN_PASSWORD_HASH');
if(!process.env.DATABASE_URL)configErrors.push('DATABASE_URL');
let sql;
try{if(process.env.DATABASE_URL)sql=neon(process.env.DATABASE_URL)}catch{configErrors.push('DATABASE_URL')}
const schemaSql=[
  `CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS tracks(id BIGINT PRIMARY KEY,title TEXT NOT NULL,artist TEXT NOT NULL,album TEXT DEFAULT '',cover_url TEXT DEFAULT '',filename TEXT NOT NULL,mime_type TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS requests(id BIGSERIAL PRIMARY KEY,song TEXT NOT NULL,artist TEXT DEFAULT '',notes TEXT DEFAULT '',user_email TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT NOW())`,
  `ALTER TABLE requests ADD COLUMN IF NOT EXISTS nickname TEXT DEFAULT ''`,
  `CREATE TABLE IF NOT EXISTS likes(user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,track_id BIGINT REFERENCES tracks(id) ON DELETE CASCADE,PRIMARY KEY(user_id,track_id))`,
  `CREATE TABLE IF NOT EXISTS playlists(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW())`,
  `CREATE TABLE IF NOT EXISTS playlist_tracks(playlist_id BIGINT REFERENCES playlists(id) ON DELETE CASCADE,track_id BIGINT REFERENCES tracks(id) ON DELETE CASCADE,position INTEGER DEFAULT 0,PRIMARY KEY(playlist_id,track_id))`
];
let schema;
const query=async(text,params=[])=>{if(!sql)throw Error('Database is not configured.');schema||=(async()=>{for(const statement of schemaSql)await sql.query(statement)})();await schema;return sql.query(text,params)};

const app=express();app.disable('x-powered-by');app.set('trust proxy',1);
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'"],imgSrc:["'self'",'data:','https:'],mediaSrc:["'self'",'blob:','https://raw.githubusercontent.com'],connectSrc:["'self'",'https://raw.githubusercontent.com'],objectSrc:["'none'"],baseUri:["'none'"],frameAncestors:["'none'"]}}}));
app.use(express.json({limit:'32kb'}),express.urlencoded({extended:false,limit:'32kb'}),cookieParser());
const authLimit=rateLimit({windowMs:900000,limit:20}),writeLimit=rateLimit({windowMs:900000,limit:60});
const clean=(v,n=200)=>String(v||'').replace(/<[^>]*>/g,'').replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,n);
function session(res,u){const token=jwt.sign({sub:String(u.id),email:u.email.toLowerCase()},SECRET,{algorithm:'HS256',expiresIn:'7d',issuer:'mases-music',audience:'web'});res.cookie('session',token,{httpOnly:true,secure:isProd,sameSite:'strict',path:'/',maxAge:604800000})}
app.use((req,_res,next)=>{try{const c=jwt.verify(req.cookies.session,SECRET,{algorithms:['HS256'],issuer:'mases-music',audience:'web'});req.user={id:String(c.sub),email:c.email,isAdmin:c.email===ADMIN}}catch{}next()});
app.use('/api',(req,res,next)=>{if(['GET','HEAD','OPTIONS'].includes(req.method))return next();return req.get('origin')===ORIGIN?next():res.status(403).json({error:'Invalid request origin.'})});
const need=(req,res,next)=>req.user?next():res.status(401).json({error:'Sign in required.'}),admin=(req,res,next)=>req.user?.isAdmin?next():res.status(403).json({error:'Forbidden.'});
const creds=z.object({email:z.string().email().max(254),password:z.string().min(10).max(128)});

app.post('/api/auth/signup',authLimit,async(req,res)=>{const p=creds.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Enter a valid email and 10+ character password.'});const email=p.data.email.toLowerCase();if(email===ADMIN)return res.status(403).json({error:'Email reserved.'});try{const hash=await bcrypt.hash(p.data.password,12),rows=await query('INSERT INTO users(email,password_hash) VALUES($1,$2) RETURNING id',[email,hash]);session(res,{id:rows[0].id,email});res.status(201).json({user:{email,isAdmin:false}})}catch(e){if(e.code==='23505')return res.status(409).json({error:'Account already exists.'});throw e}});
app.post('/api/auth/login',authLimit,async(req,res)=>{const p=creds.safeParse(req.body);if(!p.success)return res.status(401).json({error:'Invalid email or password.'});const email=p.data.email.toLowerCase();let u;if(email===ADMIN){if(!await bcrypt.compare(p.data.password,ADMIN_HASH))return res.status(401).json({error:'Invalid email or password.'});const rows=await query('INSERT INTO users(email,password_hash) VALUES($1,$2) ON CONFLICT(email) DO UPDATE SET password_hash=EXCLUDED.password_hash RETURNING id,email',[email,ADMIN_HASH]);u=rows[0]}else{const rows=await query('SELECT id,email,password_hash FROM users WHERE email=$1',[email]);u=rows[0];if(!u||!await bcrypt.compare(p.data.password,u.password_hash))return res.status(401).json({error:'Invalid email or password.'})}session(res,u);res.json({user:{email,isAdmin:email===ADMIN}})});
app.post('/api/auth/logout',(_req,res)=>{res.clearCookie('session',{httpOnly:true,secure:isProd,sameSite:'strict',path:'/'});res.sendStatus(204)});
app.get('/api/auth/me',(req,res)=>res.json({user:req.user?{email:req.user.email,isAdmin:req.user.isAdmin}:null}));
app.get('/api/health',(_req,res)=>res.status(configErrors.length?503:200).json({ok:configErrors.length===0,misconfigured:[...new Set(configErrors)]}));
app.get('/api/health/dependencies',async(_req,res)=>{const result={database:{ok:false},github:{ok:false}};try{await query('SELECT 1');result.database={ok:true}}catch(e){result.database={ok:false,error:e.code||e.name||'connection_failed'}}try{const items=await catalog();result.github={ok:true,tracks:items.length}}catch(e){result.github={ok:false,error:/GitHub read failed \(\d+\)/.exec(e.message)?.[0]||e.name||'connection_failed'}}res.status(result.database.ok&&result.github.ok?200:503).json(result)});
app.use('/api',(req,res,next)=>configErrors.length?res.status(503).json({error:'Server configuration incomplete.',misconfigured:[...new Set(configErrors)]}):next());

const ghHeaders=()=>({'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(GH_TOKEN?{'Authorization':`Bearer ${GH_TOKEN}`}:{})});
async function ghGet(file){if(!GH_REPO)return null;const url=`https://api.github.com/repos/${GH_REPO}/contents/${file}?ref=${encodeURIComponent(GH_BRANCH)}`;let r=await fetch(url,{headers:ghHeaders()});if(GH_TOKEN&&(r.status===401||r.status===403))r=await fetch(url,{headers:{'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}});if(r.status===404)return null;if(!r.ok)throw Error(`GitHub read failed (${r.status})`);return r.json()}
async function catalog(){const f=await ghGet(`${GH_DIR}/tracks.json`);return f?JSON.parse(Buffer.from(f.content.replace(/\n/g,''),'base64').toString('utf8')):[]}
async function ghPut(file,content,message,sha){if(!GH_REPO||!GH_TOKEN)throw Error('GitHub storage is not configured.');const r=await fetch(`https://api.github.com/repos/${GH_REPO}/contents/${file}`,{method:'PUT',headers:{...ghHeaders(),'Content-Type':'application/json'},body:JSON.stringify({message,content:Buffer.from(content).toString('base64'),branch:GH_BRANCH,...(sha?{sha}:{})})});if(!r.ok)throw Error(`GitHub upload failed (${r.status})`);return r.json()}
async function ghDelete(file,message,sha){if(!GH_REPO||!GH_TOKEN)throw Error('GitHub storage is not configured.');const r=await fetch(`https://api.github.com/repos/${GH_REPO}/contents/${file}`,{method:'DELETE',headers:{...ghHeaders(),'Content-Type':'application/json'},body:JSON.stringify({message,sha,branch:GH_BRANCH})});if(!r.ok)throw Error(`GitHub delete failed (${r.status})`)}
async function syncTracks(items){for(const t of items)await query(`INSERT INTO tracks(id,title,artist,album,cover_url,filename,mime_type) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO UPDATE SET title=EXCLUDED.title,artist=EXCLUDED.artist,album=EXCLUDED.album,cover_url=EXCLUDED.cover_url,filename=EXCLUDED.filename,mime_type=EXCLUDED.mime_type`,[t.id,t.title,t.artist,t.album||'',t.coverUrl||'',t.path||'',t.mimeType||'audio/mpeg'])}
app.get('/api/tracks',async(req,res)=>{const items=await catalog();let liked=new Set();if(req.user){await syncTracks(items);liked=new Set((await query('SELECT track_id FROM likes WHERE user_id=$1',[req.user.id])).map(x=>String(x.track_id)))}res.json({tracks:items.map(x=>({...x,audioUrl:`https://raw.githubusercontent.com/${GH_REPO}/${encodeURIComponent(GH_BRANCH)}/${x.path.split('/').map(encodeURIComponent).join('/')}`,liked:liked.has(String(x.id))}))})});
app.post('/api/requests',writeLimit,async(req,res)=>{const nickname=clean(req.body.nickname,40),song=clean(req.body.song,120),artist=clean(req.body.artist,120),notes=clean(req.body.notes,500);if(nickname.length<2)return res.status(400).json({error:'Enter a nickname of at least 2 characters.'});if(song.length<2)return res.status(400).json({error:'Enter a song title.'});await query('INSERT INTO requests(song,artist,notes,user_email,nickname) VALUES($1,$2,$3,$4,$5)',[song,artist,notes,req.user?.email||'',nickname]);res.status(201).json({message:'Request sent.'})});
app.post('/api/tracks/:id/like',need,async(req,res)=>{const rows=await query('SELECT 1 FROM likes WHERE user_id=$1 AND track_id=$2',[req.user.id,req.params.id]);if(rows.length)await query('DELETE FROM likes WHERE user_id=$1 AND track_id=$2',[req.user.id,req.params.id]);else await query('INSERT INTO likes(user_id,track_id) VALUES($1,$2)',[req.user.id,req.params.id]);res.json({liked:!rows.length})});
app.get('/api/playlists',need,async(req,res)=>res.json({playlists:await query(`SELECT p.id,p.name,COALESCE(json_agg(pt.track_id ORDER BY pt.position) FILTER (WHERE pt.track_id IS NOT NULL),'[]') AS "trackIds" FROM playlists p LEFT JOIN playlist_tracks pt ON pt.playlist_id=p.id WHERE p.user_id=$1 GROUP BY p.id,p.name,p.created_at ORDER BY p.created_at DESC`,[req.user.id])}));
app.post('/api/playlists',need,async(req,res)=>{const name=clean(req.body.name,60);if(!name)return res.status(400).json({error:'Name required.'});const rows=await query('INSERT INTO playlists(user_id,name) VALUES($1,$2) RETURNING id',[req.user.id,name]);res.status(201).json({playlist:{id:rows[0].id,name}})});
app.patch('/api/playlists/:id',need,async(req,res)=>{const name=clean(req.body.name,60);if(!name)return res.status(400).json({error:'Name required.'});const rows=await query('UPDATE playlists SET name=$1 WHERE id=$2 AND user_id=$3 RETURNING id,name',[name,req.params.id,req.user.id]);if(!rows.length)return res.sendStatus(404);res.json({playlist:rows[0]})});
app.delete('/api/playlists/:id',need,async(req,res)=>{const rows=await query('DELETE FROM playlists WHERE id=$1 AND user_id=$2 RETURNING id',[req.params.id,req.user.id]);res.sendStatus(rows.length?204:404)});
app.post('/api/playlists/:id/tracks',need,async(req,res)=>{const trackId=String(req.body.trackId||'');if(!/^\d+$/.test(trackId))return res.status(400).json({error:'Invalid track.'});const own=await query('SELECT 1 FROM playlists WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);if(!own.length)return res.sendStatus(404);const exists=await query('SELECT 1 FROM tracks WHERE id=$1',[trackId]);if(!exists.length)return res.status(404).json({error:'Track not found.'});await query('INSERT INTO playlist_tracks(playlist_id,track_id,position) VALUES($1,$2,(SELECT COALESCE(MAX(position),-1)+1 FROM playlist_tracks WHERE playlist_id=$1)) ON CONFLICT DO NOTHING',[req.params.id,trackId]);res.status(201).json({message:'Added to playlist.'})});
app.delete('/api/playlists/:id/tracks/:trackId',need,async(req,res)=>{const rows=await query('DELETE FROM playlist_tracks pt USING playlists p WHERE pt.playlist_id=p.id AND pt.playlist_id=$1 AND pt.track_id=$2 AND p.user_id=$3 RETURNING pt.track_id',[req.params.id,req.params.trackId,req.user.id]);res.sendStatus(rows.length?204:404)});

const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:4*1024*1024,files:1},fileFilter:(_r,f,cb)=>cb(null,['audio/mpeg','audio/mp4','audio/ogg','audio/wav','audio/webm'].includes(f.mimetype))});
function audioSig(b){return b.subarray(0,3).toString()==='ID3'||b.subarray(4,8).toString()==='ftyp'||b.subarray(0,4).toString()==='OggS'||(b.subarray(0,4).toString()==='RIFF'&&b.subarray(8,12).toString()==='WAVE')||b[0]===255}
const audioTypes={'.mp3':'audio/mpeg','.m4a':'audio/mp4','.mp4':'audio/mp4','.ogg':'audio/ogg','.wav':'audio/wav','.webm':'audio/webm'};
const isMusicFile=file=>file?.type==='file'&&Boolean(audioTypes[path.extname(file.name||'').toLowerCase()]);
app.get('/api/admin/requests',admin,async(_req,res)=>res.json({requests:await query('SELECT * FROM requests ORDER BY created_at DESC')}));
app.get('/api/admin/github-music',admin,async(_req,res)=>{const [files,items]=await Promise.all([ghGet(GH_DIR),catalog()]);const registered=new Set(items.map(x=>x.path));res.json({files:(Array.isArray(files)?files:[]).filter(isMusicFile).map(file=>({name:file.name,path:file.path,size:file.size,registered:registered.has(file.path)}))})});
app.post('/api/admin/tracks/import',admin,async(req,res)=>{const filePath=clean(req.body.path,500),title=clean(req.body.title,120),artist=clean(req.body.artist,120),album=clean(req.body.album,120),cover=clean(req.body.coverUrl,500);if(!title||!artist||(cover&&!/^https:\/\//i.test(cover)))return res.status(400).json({error:'Invalid metadata.'});if(!filePath.startsWith(`${GH_DIR}/`)||filePath.slice(GH_DIR.length+1).includes('/')||!audioTypes[path.extname(filePath).toLowerCase()])return res.status(400).json({error:'Choose a supported file from the music folder.'});const files=await ghGet(GH_DIR),selected=Array.isArray(files)&&files.find(file=>file.path===filePath&&isMusicFile(file));if(!selected)return res.status(404).json({error:'That audio file was not found in GitHub.'});const f=await ghGet(`${GH_DIR}/tracks.json`),items=f?JSON.parse(Buffer.from(f.content.replace(/\n/g,''),'base64').toString('utf8')):[];if(items.some(x=>x.path===filePath))return res.status(409).json({error:'That song is already in the library.'});const id=Date.now();items.unshift({id,title,artist,album,coverUrl:cover,path:filePath,mimeType:audioTypes[path.extname(filePath).toLowerCase()]});try{await ghPut(`${GH_DIR}/tracks.json`,JSON.stringify(items,null,2)+'\n',`Add track metadata: ${title}`,f?.sha)}catch(e){console.error(e);return res.status(502).json({error:'Could not update tracks.json. Check that GITHUB_TOKEN has Contents read/write access.'})}await syncTracks(items);res.status(201).json({id})});
app.post('/api/admin/tracks',admin,upload.single('audio'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'Supported audio required.'});if(!audioSig(req.file.buffer))return res.status(400).json({error:'Invalid audio.'});const title=clean(req.body.title,120),artist=clean(req.body.artist,120),album=clean(req.body.album,120),cover=clean(req.body.coverUrl,500);if(!title||!artist||(cover&&!/^https:\/\//i.test(cover)))return res.status(400).json({error:'Invalid metadata.'});const id=Date.now(),ext=path.extname(req.file.originalname).toLowerCase()||'.mp3',filePath=`${GH_DIR}/${crypto.randomUUID()}${ext}`;await ghPut(filePath,req.file.buffer,`Add music: ${title}`);const f=await ghGet(`${GH_DIR}/tracks.json`),items=f?JSON.parse(Buffer.from(f.content.replace(/\n/g,''),'base64').toString('utf8')):[];items.unshift({id,title,artist,album,coverUrl:cover,path:filePath,mimeType:req.file.mimetype});await ghPut(`${GH_DIR}/tracks.json`,JSON.stringify(items,null,2)+'\n',`Add track metadata: ${title}`,f?.sha);await syncTracks(items);res.status(201).json({id})});
app.patch('/api/admin/tracks/:id',admin,async(req,res)=>{const f=await ghGet(`${GH_DIR}/tracks.json`);if(!f)return res.sendStatus(404);const items=JSON.parse(Buffer.from(f.content.replace(/\n/g,''),'base64').toString('utf8')),t=items.find(x=>String(x.id)===String(req.params.id));if(!t)return res.sendStatus(404);const title=clean(req.body.title??t.title,120),artist=clean(req.body.artist??t.artist,120),album=clean(req.body.album??t.album,120),cover=clean(req.body.coverUrl??t.coverUrl,500);if(!title||!artist||(cover&&!/^https:\/\//i.test(cover)))return res.status(400).json({error:'Invalid metadata.'});Object.assign(t,{title,artist,album,coverUrl:cover});await ghPut(`${GH_DIR}/tracks.json`,JSON.stringify(items,null,2)+'\n',`Update track metadata: ${title}`,f.sha);await syncTracks(items);res.json({message:'Updated.'})});
app.delete('/api/admin/tracks/:id',admin,async(req,res)=>{const f=await ghGet(`${GH_DIR}/tracks.json`);if(!f)return res.sendStatus(404);const items=JSON.parse(Buffer.from(f.content.replace(/\n/g,''),'base64').toString('utf8')),index=items.findIndex(x=>String(x.id)===String(req.params.id));if(index<0)return res.sendStatus(404);const [track]=items.splice(index,1);await ghPut(`${GH_DIR}/tracks.json`,JSON.stringify(items,null,2)+'\n',`Remove track: ${track.title}`,f.sha);try{const audio=await ghGet(track.path);if(audio?.sha)await ghDelete(track.path,`Delete audio: ${track.title}`,audio.sha)}catch(e){console.error('Audio cleanup failed',e)}await query('DELETE FROM tracks WHERE id=$1',[req.params.id]);res.sendStatus(204)});

app.use(express.static(path.join(__dirname,'public'),{extensions:['html']}));app.get('/{*path}',(_req,res)=>res.sendFile(path.join(__dirname,'public/index.html')));
app.use((e,_req,res,_next)=>{console.error(e);res.status(e.code==='LIMIT_FILE_SIZE'?413:500).json({error:'Request could not be completed.'})});
if(require.main===module)app.listen(PORT,()=>console.log(`Mase's Music listening on ${PORT}`));
module.exports=app;
